### ISSUE TITLE
Rust libraries

### ISSUE THREAD

**Issue by kahveciderin** [Caerind/AwesomeCppGameDev#17]
Why are rust libraries on this list?

**Comment by Caerind** [comment]
I added some Rust projects to the list as I know that some programmers are now learning Rust for game programming.
As Rust libraries aren't the main objective of this project, they are in their own category. 

If you have seen some libraries that were not in the Rust category, tell me or you can PR it :)

**Comment by kahveciderin** [comment]
oh ok thanks
